-- AlterTable
ALTER TABLE `Maillog` ADD COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `instance` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `recipients_domains` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `sender_domain` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `session_id` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `size` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `subject` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `tls` INTEGER NOT NULL DEFAULT 0;
